/*
 * Copyright (C) 2010 Manuel Luitz
 *
 * This file is part of AndroHid.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; If not, see <http://www.gnu.org/licenses/>.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_androhid_NativeBtHid */

#ifndef _Included_org_androhid_NativeBtHid
#define _Included_org_androhid_NativeBtHid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_androhid_NativeBtHid
 * Method:    setupClient
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_androhid_NativeBtHid_setupClientSocket
  (JNIEnv *, jobject);

/*
 * Class:     org_androhid_NativeBtHid
 * Method:    connectToHost
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_androhid_NativeBtHid_connectToHost
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_androhid_NativeBtHid
 * Method:    deconnectClient
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_androhid_NativeBtHid_deconnectClient
  (JNIEnv *, jobject);

/*
 * Class:     org_androhid_NativeBtHid
 * Method:    sendKeyDownEvent
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_androhid_NativeBtHid_sendKeyDownEvent
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_androhid_NativeBtHid
 * Method:    sendKeyUpEvent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_androhid_NativeBtHid_sendKeyUpEvent
  (JNIEnv *, jobject);

/*
 * Class:     org_androhid_NativeBtHid
 * Method:    sendMouseEvent
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_org_androhid_NativeBtHid_sendMouseEvent
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     org_androhid_NativeBtHid
 * Method:    isEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_androhid_NativeBtHid_isEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_androhid_NativeBtHid
 * Method:    btDeviceScan
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_androhid_NativeBtHid_btDeviceScan
  (JNIEnv *, jobject);

/*
 * Class:     org_androhid_NativeBtHid
 * Method:    btDeviceGetName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_androhid_NativeBtHid_btDeviceGetName
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
